name: Deploy to Railway

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fitness_chatbot .

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Login via Token (Non-Interactive)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 
        
      - name: Deploy to Railway
        env:
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway up --project $RAILWAY_PROJECT_ID \
            --service my-chatbot \
            --docker-image fitness_chatbot
